# Use an official language runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the rest of your application code
COPY . .

# Match the port Cloud Run expects (usually 8080)
ENV PORT=8080
EXPOSE 8080

# Start the application
CMD [ "npm", "start" ]